version: "3.4"

volumes:
  mysqldata:
    driver: local

services:
  server:
    build: .
    volumes:
      - .:/var/www/html
    ports:
      - 9077:80

  db:
    # container_name: db
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'supersecret'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_DATABASE: 'swisstattooartistes'
    volumes:
      - ./mysqldata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
    depends_on:
      - db

